### PR TITLE
Update 000-index.md

### PR DESCRIPTION
**Pull request by qt-luigi**
fix typo.

### CODE REVIEW

**Comment by kjk** [comment]
Thanks for all  the fixes.

I've added you as a collaborator to the project. If you prefer, feel free to checkin directly into the repository.

**Comment by qt-luigi** [comment]
Hello, kjk! Thanks for inviting me. Sorry, I mistook GitHub operation and deleted your collaborator invention message. If you possible invite me, Please invite me again!

**Comment by kjk** [comment]
No worries, I've re-invited.

**Comment by qt-luigi** [comment]
Thank you so much! This book is very huge. I think that you are a great to write it! I am challenging to read this book now. I was sending a PR instead of a my bookmark. :-P Sorry and Thanks!

**Pull request merged**
